# Do NOT update manually; changes here will be overwritten by Copier
_commit: 0f6de6d
_src_path: gh:open-synergy/ssi-addons-repo-template
dependency_installation_mode: OCA
generate_requirements_txt: false
include_aeroo_report: true
include_wkhtmltopdf: true
odoo_version: 8.0
rebel_module_groups: []
repo_description: opnsynid-account-voucher-aeroo-report
repo_name: opnsynid-account-voucher-aeroo-report
repo_slug: opnsynid-account-voucher-aeroo-report
travis_apt_packages:
  - libcups2-dev
  - cups
travis_apt_sources: []
